### ISSUE TITLE
经该仓库方式部署的 Mx-space 前端和后台均无法链接上 API 后端 

### ISSUE THREAD

**Issue by ghost** [mx-space/docker#2]
在参照项目 Readme.md 文件的操作进行部署之后前端和后台均无法连接上后端。在参照 [老文档有关 Caddy 反向代理的设置](https://github.com/mx-space/docs/blob/master/old/reverse-proxy.md) 修改 `Caddyfile` 之后，后台可链接上 API 后端，但前端 kami 仍显示“无数据”

**Comment by ttimochan** [comment]
那你进行 kami v3配置了么？

**Comment by ghost** [comment]
> 那你进行 kami v3配置了么？

问题都鸽了两个月了才回（我都在群里问过了
目前没整最新版本不知道还会不会复现这个问题（

**Comment by ttimochan** [comment]
emmm，这个仓库我没怎么关注，如果提问题应该去docs，最新版的问题应该被innei修复了
